.model small
.stack 64
.data
LIST dB 03H, 04H, 01H, 02H
MIN dB 007FH
MAX dB 0000H
.code
START: 	MOV AX, @DATA
		MOV DS, AX
		MOV CX, 0004H
		LEA SI, LIST
		L1:	MOV AL, [SI]
			CMP AL, MIN
			JLE PUTMIN
		L2:	CMP AL, MAX
			JGE PUTMAX
		L3:	INC SI
			LOOP L1
		STOP: RET
		PUTMIN:	MOV MIN, AL
				JMP L2
		PUTMAX:	MOV MAX, AL
				JMP L3
		MOV AH, 4CH
		INT 21H
END START